services:
  - type: web
    name: stanmoudev-service-hub
    env: python
    buildCommand: python -m pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    rootDir: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: local-services-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: DEBUG
        value: "False"
    healthCheckPath: /admin/login/
    autoDeploy: true
