# Generated by Django 5.2.6 on 2025-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_pics/'),
        ),
    ]
